### ISSUE TITLE
Alpine image

### ISSUE THREAD

**Issue by grzesuav** [Michael-F-Bryan/mdbook-docker-image#4]
Provide or switch to alpine instead of ubuntu, should be smaller

**Comment by Michael-F-Bryan** [comment]
I don't think an alpine build will provide much benefit.

The docker image based on Ubuntu is currently a 69.66 MB download, with a big majority of that space being taken up by `mdbook` and the various plugin binaries.

For an example of how much space the executables use, I've got about 60 MB of `mdbook`-related binaries on my computer.

```
$ du -h ~/.cargo/bin/mdbook*
17M	/home/michael/.cargo/bin/mdbook
19M	/home/michael/.cargo/bin/mdbook-linkcheck
7.9M	/home/michael/.cargo/bin/mdbook-mermaid
4.8M	/home/michael/.cargo/bin/mdbook-toc
```

I don't feel that shaving 5-10 MB off a download is worth the extra maintenance hassle of keeping multiple Dockerfiles in sync and troubleshooting all the issues related to making sure OpenSSL gets cross-compiled properly (e.g. `mdbook-linkcheck` needs OpenSSL to check HTTPS links).
