### ISSUE TITLE
Docs: add note that graphviz plugin require installed graphviz bin

### ISSUE THREAD

**Issue by grzesuav** [Michael-F-Bryan/mdbook-docker-image#5]
Either add to readme that standalone installation is needed or bundle it with image

**Comment by Michael-F-Bryan** [comment]
Shouldn't everything you need be already installed inside the docker image? If it isn't, we'll need to update the Dockerfile to include graphviz.

The main point of using these docker images is that people shouldn't need to install anything to be able to use `mdbook`.

**Comment by grzesuav** [comment]
ok, will add this. I forgot to do it in previous PR.

**Comment by grzesuav** [comment]
https://github.com/Michael-F-Bryan/mdbook-docker-image/pull/6
